source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ForceTouchable_Example', :exclusive => true do
  pod 'ForceTouchable', :path => '../'
end

target 'ForceTouchable_Tests', :exclusive => true do
  pod 'ForceTouchable', :path => '../'

  
end
